import { Card } from '../interfaces/common';

export const heroquestCardsMock: Card[] = [
  {
    id: 1,
    type: 'Treasure',
    name: 'Potion of Healing',
    isFavorite: true,
    collectionId: 101,
    imageUrl: '/assets/card3.png',
    userId: 1,
    createDate: new Date('2024-01-10'),
  },
  {
    id: 2,
    type: 'Artifact',
    name: 'Spirit Blade',
    isFavorite: false,
    collectionId: 102,
    imageUrl: '/assets/card2.png',
    userId: 1,
    createDate: new Date('2024-01-12'),
  },
  {
    id: 3,
    type: 'Monster',
    name: 'Gargoyle',
    isFavorite: true,
    collectionId: 103,
    imageUrl: '/assets/card3.png',
    userId: 2,
    createDate: new Date('2024-01-15'),
  },
  {
    id: 4,
    type: 'Hero',
    name: 'Barbarian',
    isFavorite: false,
    collectionId: 104,
    imageUrl: '/assets/card3.png',
    userId: 3,
    createDate: new Date('2024-01-17'),
  },
  {
    id: 5,
    type: 'Treasure',
    name: 'Gold Coins',
    isFavorite: false,
    collectionId: 101,
    imageUrl: '/assets/card2.png',
    userId: 1,
    createDate: new Date('2024-01-20'),
  },
  {
    id: 6,
    type: 'Monster',
    name: 'Orc',
    isFavorite: true,
    collectionId: 103,
    imageUrl: '/assets/card3.png',
    userId: 2,
    createDate: new Date('2024-01-22'),
  },
  {
    id: 7,
    type: 'Hero',
    name: 'Elf',
    isFavorite: false,
    collectionId: 104,
    imageUrl: '/assets/card2.png',
    userId: 3,
    createDate: new Date('2024-01-25'),
  },
  {
    id: 8,
    type: 'Spell',
    name: 'Wizard’s Staff',
    isFavorite: true,
    collectionId: 102,
    imageUrl: '/assets/card2.png',
    userId: 1,
    createDate: new Date('2024-01-27'),
  },
  {
    id: 9,
    type: 'Treasure',
    name: 'Jewels',
    isFavorite: false,
    collectionId: 101,
    imageUrl: '/assets/card3.png',
    userId: 2,
    createDate: new Date('2024-01-30'),
  },
  {
    id: 10,
    type: 'Monster',
    name: 'Fimir',
    isFavorite: true,
    collectionId: 103,
    imageUrl: '/assets/card2.png',
    userId: 2,
    createDate: new Date('2024-02-02'),
  },
];
